### ISSUE TITLE
Junction needs a name

### ISSUE THREAD

**Issue by dcarosone** [philam/melbournebikemap#24]
the junction between Clifton Hill and East Kew needs a name, though I appreciate it might have been left off for space and layout reasons.
![image](https://user-images.githubusercontent.com/11495017/41827284-e0a46b90-7871-11e8-9d38-f400a8552999.png)
I suggest "Yarra Bend".

**Comment by philam** [comment]
Thanks for the request! I'll give it a go and see how it turns out.

**Comment by philam** [comment]
Added
