### ISSUE TITLE
Route codes

### ISSUE THREAD

**Issue by ehbert** [philam/melbournebikemap#42]
All the trails around Melbourne have safety codes for emergencies. These codes are continuously signed along the trails with a 3letter trail code follows by a changing numerical distance code so emergency services can locate people e.g Dandenong creek might be DCT or CCT for capital city trail. It would be great if your map codes mimicked the codes already associated to all the trails.

**Comment by philam** [comment]
Thanks for the idea! I know that the ESTA has allocated codes for most of the major trails, but as far as I'm aware there are still many trails without these three letter codes, particularly some of the minor trails.

I will have a look though and see if I can use the ones that do exist, then make up the other ones myself :)

**Comment by philam** [comment]
Realised that these are three letter codes, whereas my current map uses two. Given that this will be quite a large task to change, I'm moving this to the v1.1 milestone for future implementation.

**Comment by alexisolavarria** [comment]
Hey Phil, 
Hows the three letter codes for the trails?

**Comment by philam** [comment]
@alexisolavarria Will update it in the next version, hopefully some time next month

**Comment by philam** [comment]
Added them into draft v1.1 version, coming out soon
